title = "My awesome website"

[params.author]
name = "Mikołaj Pawłowski"
bio = "lorem ipsum costam costam"
links = [
	{ name = "github", link = "https://www.github.com/krecony", icon = "github" },
	{ name = "linkedin", link = "https://www.linkedin.com/in/miko%C5%82aj-paw%C5%82owski/", icon = "linkedin" },
	{ name = "email", link = "mailto:pawlowski.mikolaj@proton.me", icon = "at-sign" },
	{ name = "codeforces", link = "https://codeforces.com/profile/krecony", icon = "bar-chart-2" },
]
