[[main]]
name = 'home'
pageRef = '/'
weight = 1

[[main]]
name = 'portfolio'
pageRef = '/portfolio'
weight = 2

[[main]]
name = 'posts'
pageRef = '/posts'
weight = 3

[[main]]
name = 'projects'
pageRef = '/projects'
weight = 4
